name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Chekout Code
        uses: actions/checkout@v2
      -
        name: Setup NodeJS
        uses: actions/setup-node@v2
      - 
        name: Build artifacts
        env:
          # The JSON-RPC URL of the blockchain cluster (https) https://blockemon-2022.trapesys.io:8545/
          REACT_APP_POLYGON_EDGE_API: https://rpc.poa.psdk.io:8545

          # The Chain ID of the blockchain cluster (in hex format, with 0x..)
          REACT_APP_POLYGON_EDGE_CHAIN_ID: "0x64"

          # The Ethereum Address of the deployed MVPT ERC-20 contract
          REACT_APP_MVPT_ADDRESS: "0x3e5dB28b22Fa5355607b4F2EeB3c738D3CB9FDe9"

          # The Ethereum Address of the deployed MVPTicketSale contract
          REACT_APP_TICKET_SALE_ADDRESS: "0xdBFd1f46eAF17CfFddB4b05a8b07f2283eC09fE3"
          # Don't treat build warnings as errors
          CI: false
        run: |
          cd web-ui
          npm install
          yarn build
      # Deploy to local branch
      - name: Deploy build to local branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: artifacts
          FOLDER: web-ui/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}